apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.appName}}-depl"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-svc
  template:
    metadata:
      name: "{{.Values.appName}}-pod"
      labels:
        app: chat-svc
    spec:
      containers:
        - name: chat-svc
          image: devhik0/crm-saas-chat-svc:latest
          resources:
            requests:
              memory: 20Mi
              cpu: 20m
            limits:
              memory: 50Mi
              cpu: 50m

---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.appName}}-srv"
spec:
  type: NodePort
  selector:
    app: chat-svc
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
