apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-svc-depl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-svc-depl
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
