/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as categories from "../categories.js";
import type * as contacts from "../contacts.js";
import type * as helpTickets from "../helpTickets.js";
import type * as tasks from "../tasks.js";
import type * as tickets from "../tickets.js";
import type * as trackers from "../trackers.js";
import type * as transactions from "../transactions.js";
import type * as visitors from "../visitors.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  categories: typeof categories;
  contacts: typeof contacts;
  helpTickets: typeof helpTickets;
  tasks: typeof tasks;
  tickets: typeof tickets;
  trackers: typeof trackers;
  transactions: typeof transactions;
  visitors: typeof visitors;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
