name: Deploy Pipeline (Chat Service)
on:
  push:
    paths:
      - "./services/chat-svc/**"
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Format App
        run: bun run format

  # todo: add here after adding tests
  # test:
  #   name: Test
  #   needs: format
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Bun
  #       uses: oven-sh/setup-bun@v1

  #     - name: Install Dependencies
  #       run: bun install

  #     - name: Test App
  #       run: bun run test

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USER }}/crm-saas-chat-svc:latest
          platforms: linux/amd64,linux/arm64/v8
      
# todo: add k8 steps and more
